MOOCCubeX:
  data_path: './datasets'
  batch_size_train: 128
  batch_size_test: 128
  topk: [10, 20, 40, 80]
  neg_num: 2

  # the following are the best settings
  aug_type: "ED"
  ed_interval: 1
  embedding_sizes: [128]
  num_layerss: [1]
  lrs: [1.0e-3]
  item_level_ratios: [0.2]
  bundle_level_ratios: [0.2]
  bundle_agg_ratios: [0]
  l2_regs: [4.0e-5]

  c_lambdas: [0.04]
  c_temps: [0.2]

  epochs_teacher: 50
  epochs_student: 50
  test_interval: 50

  ub_weights: 0.3
  max_seq_len: 50

  l2_dis: [1.00E-05, 2.00E-05]

Ednet:
  data_path: './datasets'
  batch_size_train: 128
  batch_size_test: 128
  topk: [10, 20, 40, 80]
  neg_num: 2

  # the following are the best settings
  aug_type: "ED"
  ed_interval: 1
  embedding_sizes: [128]
  num_layerss: [3]
  lrs: [1.0e-3]
  item_level_ratios: [0.2]
  bundle_level_ratios: [0.2]
  bundle_agg_ratios: [0]
  l2_regs: [4.0e-5]

  c_lambdas: [0.04]
  c_temps: [0.2]

  epochs_teacher: 50
  epochs_student: 50
  test_interval: 50

  ub_weights: 0.3
  max_seq_len: 50

  l2_dis: [1.00E-05]